# CI for Chain on macOS-11 Environment
name: Build Ternoa Client MacOS

on:
  workflow_run:
    workflows: 
      - Linux-Environment
    types:
      - completed
    tags:
      - v1.*
  workflow_dispatch:
    inputs:
      ignoreLevel:
        description: 'Ignore'
        default: 'ignore'
        type: choice
        options:
        - ignore


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-11 
    steps:
    - uses: actions/checkout@v3

    - name: Install Brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" -y 

    - name: Updating Brew Packages
      run: brew update

    - name: Brew install required packages
      run: brew install openssl cmake llvm
  
    - name: Install Rustup
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: Load env
      run: source ~/.cargo/env

    - name: rustup default stable
      run: rustup default stable

    - name: rustup update
      run: rustup update

    - name: rustup update nightly
      run: rustup update nightly

      
    - name: rustup target add wasm32-unknown-unknown --toolchain nightly
      run: rustup target add wasm32-unknown-unknown --toolchain nightly

    - name: Load env
      run: source ~/.cargo/env

    - name: rustc --version
      run: rustc --version

    - name: rustup show
      run: rustup show


    - name: Build
      run: cargo build --release

#    - name: Test 
#      run: cargo test --all-targets --all-features --workspace

    - name: Configure AWS credentials from Test account
      uses: s3-actions/s3cmd@v0
      with:
        provider: "aws"
        access_key: ${{ secrets.SW_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.SW_SECRET_ACCESS_KEY }}
        region: fr-par
        
    - name: Copy Binary to Scaleway Bucket /chain/${GITHUB_REF##*/}/latest
      run: |
        s3cmd sync ./target/release/ternoa s3://ternoa/chain/${GITHUB_REF##*/}/macos/ternoa --host https://s3.fr-par.scw.cloud --host-bucket https://s3.fr-par.scw.cloud  --acl-public

    - name: Copy Binary to Scaleway Bucket  ${{ github.sha }}.zip
      run: |
        s3cmd sync ./target/release/ternoa s3://ternoa/chain/${GITHUB_REF##*/}/macos/${{ github.sha }} --host https://s3.fr-par.scw.cloud --host-bucket https://s3.fr-par.scw.cloud  --acl-public
        
    - name: Notify Ops
      uses: craftech-io/slack-action@v1
      with:
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
